using Serenity.Navigation;
using MyPages = FormulationManagementSystems.VDSCSQL.Pages;

[assembly: NavigationLink(int.MaxValue, "VDSCSQL/Additon Form", typeof(MyPages.AdditonFormController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "VDSCSQL/Bulk Batch", typeof(MyPages.BulkBatchController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "VDSCSQL/Bulk Batch Data", typeof(MyPages.BulkBatchDataController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "VDSCSQL/Bulk Scan", typeof(MyPages.BulkScanController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "VDSCSQL/Bulk Storage Tank", typeof(MyPages.BulkStorageTankController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "VDSCSQL/Consumption", typeof(MyPages.ConsumptionController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "VDSCSQL/Customer", typeof(MyPages.CustomerController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "VDSCSQL/Employee", typeof(MyPages.EmployeeController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "VDSCSQL/Employee Overtime", typeof(MyPages.EmployeeOvertimeController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "VDSCSQL/Employee Photo", typeof(MyPages.EmployeePhotoController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "VDSCSQL/Manager", typeof(MyPages.ManagerController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "VDSCSQL/Material", typeof(MyPages.MaterialController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "VDSCSQL/Production Request", typeof(MyPages.ProductionRequestController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "VDSCSQL/Recipe", typeof(MyPages.RecipeController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "VDSCSQL/Recipe Phase", typeof(MyPages.RecipePhaseController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "VDSCSQL/Src Dst Path", typeof(MyPages.SrcDstPathController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "VDSCSQL/Srl Bulk Movement", typeof(MyPages.SrlBulkMovementController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "VDSCSQL/Srl Bulk Movement Data", typeof(MyPages.SrlBulkMovementDataController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "VDSCSQL/Srl Bulk Storage Tank Data", typeof(MyPages.SrlBulkStorageTankDataController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "VDSCSQL/Srl Bulk Terminal Clearance", typeof(MyPages.SrlBulkTerminalClearanceController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "VDSCSQL/Srl Carrier", typeof(MyPages.SrlCarrierController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "VDSCSQL/Srl Msds", typeof(MyPages.SrlMsdsController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "VDSCSQL/Step Instruction", typeof(MyPages.StepInstructionController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "VDSCSQL/Step Instruction Type", typeof(MyPages.StepInstructionTypeController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "VDSCSQL/Step Value Entries", typeof(MyPages.StepValueEntriesController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "VDSCSQL/Value Entries Data", typeof(MyPages.ValueEntriesDataController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "VDSCSQL/Valve List", typeof(MyPages.ValveListController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "VDSCSQL/Valve Position Map", typeof(MyPages.ValvePositionMapController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "VDSCSQL/Vdsc Area", typeof(MyPages.VdscAreaController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "VDSCSQL/Vdsc Area Group", typeof(MyPages.VdscAreaGroupController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "VDSCSQL/Vdsc Department", typeof(MyPages.VdscDepartmentController), icon: null)]